name: learning-workflows
on: workflow_dispatch
jobs:
  Everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm run ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build
